[package]
name = "cae"
version = "1.1.0"
edition = "2021"

[dependencies]
wgpu = "22.1"
winit = "0.30"
pollster = "0.3"
env_logger = "0.11"
log = "0.4"
clap = { version = "4.5", features = ["derive"] }
bytemuck = { version = "1.14", features = ["derive"] }
